Repository projectsyn/component-velero, pull requests merged in 2021-07, with the labels that each got.

#1 Helm chart output path
  class/defaults.yml
  class/velero.yml
  component/velero-backupstoragelocation.libsonnet
  component/velero-schedule.libsonnet
  component/velero-secret.libsonnet
  component/velero-volumesnapshotlocation.libsonnet
Labels: enhancement

#2 Use the cloud fact instead of a fixed provider as default
  class/defaults.yml
Labels: enhancement

#3 Documentation update and howto
  README.md
  class/defaults.yml
  docs/modules/ROOT/pages/how-tos/aws.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: documentation

#4 Disable Helm own backup and snapshot objects
  class/defaults.yml
Labels: bug
